### ISSUE TITLE
cangw error on Raspberry Pi 3 PiCAN2 Duo

### ISSUE THREAD

**Issue by rg4444** [linux-can/can-utils#111]
Running cangw commands (cangw -F) on raspberry Pi 3 return error:
`netlink error -1 (Operation not permitted)`
Linux kernel: Linux/arm 4.14.71, mod-gw enabled
`modprobe can-gw` returns no error.
CAN board - PICAN2 DUO, CAN0 and CAN1 interfaces are up and running.
Any instructions to enable cangw?

I have posted the same issue here: https://github.com/raspberrypi/linux/issues/2726

**Comment by marckleinebudde** [comment]
Try to run `cangw` as the `root` user.

**Comment by rg4444** [comment]
`sudo cangw` works
Thank you!
