### ISSUE TITLE
can-gw ; help ORing and XORing

### ISSUE THREAD

**Issue by psyolent** [linux-can/can-utils#115]
Just after a little help with my understanding of incrementing a value. I have a value which i've masked with FF (tach value) which comes on PID 180. The value changes (as a tach does) however while the static OR of FF to the value that comes in allows me to the XOR it to the value I need ; as the incoming value changes so does that of the XOR. 

In the case of a value 3F hex coming in, if I OR it with FF then XOR it with AB it becomes hex 54 which is what I need. With the next value hex 40 however, then I OR it with FF my XOR value changes to 85 to make hex 55 which is what i need. 

The command as below is what I have come up with. I've not executed it as my test vehicle is some distance away which is annoying. I'm only working on the logic.

cangw -A -e -s vcan0 -d vcan1 -f 180:FF -m SET:IL:308.8.0000000000000000 -m OR:D:308.8.FF00000000000000 -m XOR:D:308.8.AB00000000000000

EDIT : just testing my command. it failed
EDIT : updated command. the XOR'd value is correct (54) on PID 308 however as the incoming value on 180 changes, 308 does not. It stays static.

Advice very welcomed. Ta.

**Comment by hartkopp** [comment]
I assume you did not take into account that the **order of modifications** is fixed inside the can-gw kernel module:

https://github.com/linux-can/can-utils/blob/master/cangw.c#L219
`The max. four modifications are performed in the order AND -> OR -> XOR -> SET`

If you have different CAN-IDs you want to modify I would suggest to create multiple cangw jobs.

Additionally the filter `180:FF` looks incomplete. If you want to filter for a single SFF frame the mask should look like `-f 180:C00007FF` (see `candump`help text).

**Comment by psyolent** [comment]
--> I assume you did not take into account that the order of modifications is fixed inside the can-gw kernel module:
dammit, i have my SET at the start - thanks for pointing that out mate. ta.

--> If you have different CAN-IDs you want to modify I would suggest to create multiple cangw jobs.
yes for the different PIDs different rules - no problems. 

--> Additionally the filter 180:FF looks incomplete. If you want to filter for a single SFF frame the mask should look like -f 180:C00007FF (see candumphelp text).
ok. will do more research. 

thanks for your input and help - very appreciated
