### ISSUE TITLE
can_if says network down

### ISSUE THREAD

**Issue by daverathbone** [linux-can/can-utils#125]
I need can up after boot and used Oliver Hartkopp's can_if script with my can ports, and invoked but it does not start on power up into CAN but says network down. Am I missing somthing?

**Comment by hartkopp** [comment]
After copying `can_if` to `/etc/init.d` you need to invoke
`update-rc.d can_if defaults`

This should create the relevant symbolic links to run the script on startup.
See http://manpages.ubuntu.com/manpages/xenial/man8/update-rc.d.8.html
