### ISSUE TITLE
Add 2 examples for sending the same can frame with can_id as SFF and with EFF

### ISSUE THREAD

**Issue by jogo-** [linux-can/can-utils#126]
https://github.com/linux-can/can-utils/blob/2328c6cfa0b004173644796a3604392f355dcde2/cansend.c#L85-L87

`fprintf(stderr, "7FF#05FF for SFF / 000007FF#0EFF for EFF\n");`

This example should be clear enough and could help.

**Comment by hartkopp** [comment]
There are two lines holding Classic CAN / CAN FD and '.' separated content for SFF/EFF examples.
I don't get your idea for an improvement.

**Comment by jogo-** [comment]
It's just to clarify how to send the same frame with the same id as SFF or as EFF

**Comment by hartkopp** [comment]
What about this as an example?
```
e.g. 5A1#11.2233.44556677.88 / 123#DEADBEEF / 5AA# / 123##1 / 213##311223344
     1F334455#1122334455667788 / 123#R / 00000123#R3
```

**Comment by jogo-** [comment]
Ok, but:
`e.g. 5A1#11.2233.44556677.88 / 123#DEADBEEF / 5AA# / 123##1 / 213##311223344
     1F334455#1122334455667788 / 123#R / 7FF#05FF / 000007FF#0EFF`
is a funny way to clarify things using hexspeak (as in DEADBEEF) ;-)

**Comment by hartkopp** [comment]
Reading source code must be fun :-D
