### ISSUE TITLE
candump warning does not end with newline

### ISSUE THREAD

**Issue by VictorSCushman** [linux-can/can-utils#150]
Logging to a file and standard output with `-s0` causes the first message read to begin with a `Warning` on standard output without a terminating newline. This makes it more difficult to perform text manipulation on standard output.

**CANSEND TERMINAL:**

```sh
$ cansend vcan0 123#8899AABBCCDDEEFF
$ cansend vcan0 123#0011223344556677
$ cansend vcan0 123#0123456789ABCDEF
```

**CANDUMP TERMINAL:**

```sh
$ candump -c -L -l -s0 vcan0


Enabling Logfile 'candump-2019-08-23_095535.log'

Warning: console output active while logging!(1566568538.151984) vcan0 123#8899AABBCCDDEEFF
(1566568550.735820) vcan0 123#0011223344556677
(1566568568.788899) vcan0 123#0123456789ABCDEF
```

**Comment by hartkopp** [comment]
Hi Victor,
fixed both the formatting issue and the fact that in silent mode the logfile format still created some output.
Thanks for the report! I added you in the credits for the patch.
Thanks,
Oliver

**Comment by VictorSCushman** [comment]
Thanks for the quick response @hartkopp!
