### ISSUE TITLE
No response to the candump on v3msk

### ISSUE THREAD

**Issue by Prasad454** [linux-can/can-utils#152]
Hello,

I want to test CAN Application on Linux environment. For this i have cross compiled the can-utils and loaded into the /nfs folder in my board. 
1. After sending the cansend i dont see any CAN traffic on candump

![image](https://user-images.githubusercontent.com/53291749/63906143-58a2d300-ca49-11e9-9965-edf5919729cc.png)

2. Sometimes when i send cansend i see some error messages as below
![image](https://user-images.githubusercontent.com/53291749/63906194-9869ba80-ca49-11e9-912c-28a92e30d53d.png)

Can someone help me on these topics?

**Comment by hartkopp** [comment]
Duplication with https://github.com/linux-can/can-utils/issues/128#issuecomment-526000069
