### ISSUE TITLE
 Networking with CAN-J1939 support - documentation networking/j1939.rst 

### ISSUE THREAD

**Issue by josemic** [linux-can/can-utils#174]
This is a follow-up issue of #159.
[networking/j1939.rst](https://github.com/torvalds/linux/blob/master/Documentation/networking/j1939.rst)
 referes to J1939_PGN_ADDRESS_REQUEST, however "j1939.h" defines only:
#define J1939_PGN_REQUEST 0x0ea00

There was once a patch changing the define "J1939_PGN_REQUEST" to "J1939_PGN_ADDRESS_REQUEST". However this patch had been rejected. Still the documentation [networking/j1939.rst](https://github.com/torvalds/linux/blob/master/Documentation/networking/j1939.rst) had been written as if this patch had been applied: 
[Link to patch](https://marc.info/?l=linux-can&m=155491812521734&w=2)

This  [networking/j1939.rst](https://github.com/torvalds/linux/blob/master/Documentation/networking/j1939.rst) needs to be changed as following (search for "J1939_PGN_ADDRESS_COMMANDED", add the line marked below with "+" and remove the line marked below with "-"):
```
const struct j1939_filter filt[] = {
        {
                .pgn = J1939_PGN_ADDRESS_CLAIMED,
                .pgn_mask = J1939_PGN_PDU1_MAX,
        }, {
-                .pgn = J1939_PGN_ADDRESS_REQUEST,
+                .pgn = J1939_PGN_REQUEST,
                .pgn_mask = J1939_PGN_PDU1_MAX,
        }, {
                .pgn = J1939_PGN_ADDRESS_COMMANDED,
                .pgn_mask = J1939_PGN_MAX,
        },
};
```

**Comment by marckleinebudde** [comment]
I'll include this fix in my next pull request to net/master.
