### ISSUE TITLE
can-j1939-kickstart.md - Binding a can-j1939 socket to a source address will register

### ISSUE THREAD

**Issue by josemic** [linux-can/can-utils#178]
From can-j1939-kickstart.md line 57:
> ### Use source address
> 
> Binding a can-j1939 socket to a source address will register
> allow you to send packets.
> 
> 	./testj1939 can0:0x80
> 
> Your system had, for a small moment, source address 0x80 assigned.

I do not understand the sentence: 
> Binding a can-j1939 socket to a source address will register
> allow you to send packets.
Should likely mean:
Binding a can-j1939 socket to a source address will register and allow you to send packets.

Please rephrase.

**Comment by marckleinebudde** [comment]
This is fixed by: https://github.com/linux-can/can-utils/pull/175
