### ISSUE TITLE
Doubts: Message Recovery

### ISSUE THREAD

**Issue by alfonsobrandao** [linux-can/can-utils#185]
Hey everyone!

Having some trouble leading with message recovery, is there any way of finding if the message was fully sent or some callback in case it doesn't happen?

Thanks is advance!
Alfonso

**Comment by hartkopp** [comment]
Hi Alfonso!
I assume you a referring to https://github.com/hartkopp/can-isotp .
Can you please file an issue there as the question is not really can-utils related.
Thanks,
Oliver

**Comment by alfonsobrandao** [comment]
Hey Hartkopp!

Already post it there! 

Thanks in advance,
Alfonso

**Comment by hartkopp** [comment]
Thanks :-)
