### ISSUE TITLE
New release?

### ISSUE THREAD

**Issue by Bastian-Krause** [linux-can/can-utils#187]
Hi,

the last (and only) release was quite a long time ago. It would be nice to have a more recent one which could then end up in a recent Debian package.

Regards,
Bastian

**Comment by a3f** [comment]
Preferably, this release could include the PTX flavour can-utils like cansequence as well!

**Comment by hartkopp** [comment]
I would also vote for a new tag v2020.02.0
Especially due to the fact, that the code is stored in a mountain in some day :-)

**Comment by hartkopp** [comment]
And there we are with a new tag!
https://github.com/linux-can/can-utils/releases/tag/v2020.02.0
Thanks to @Bastian-Krause for the reminder!
For the next step/tag we could hopefully really enable cansniffer for 29bit IDs and CAN FD - and to create man pages for the tools. :-D

**Comment by Bastian-Krause** [comment]
Thanks!
