### ISSUE TITLE
candump empty

### ISSUE THREAD

**Issue by stapperfend** [linux-can/can-utils#188]
Hello, the candump for us is empty when we try to read out can0. Reading out vcan works fine using the same setup and commands. We use canopensocket

**Comment by hartkopp** [comment]
Hi. I would assume that you have not set up the can0 interface properly (e.g. bitrate, setting the interface to 'up') or that you don't have any traffic on the bus or a missing CAN bus termination.
When candump works on vcan0 it should be able to read from can0 in the same way.

**Comment by stapperfend** [comment]
We used it before

**Comment by hartkopp** [comment]
You used what?

**Comment by stapperfend** [comment]
> You used what?

Didn't mean to send the response. Sorry. We used candump before. So we thought our issue might be with an update of can_utils.

**Comment by hartkopp** [comment]
You are using the mttcan which is a NVIDIA out of tree CAN driver. I would suggest to look into that direction (and probably the sampling-point option).
The can-utils (and especially candump) should not have changed in a way that it has an effect to your updated setup.

**Comment by stapperfend** [comment]
okay. Thank you a lot for your time.
That helps us isolating the error.
