### ISSUE TITLE
listen-only in slcand

### ISSUE THREAD

**Issue by interlocuteur** [linux-can/can-utils#19]
slcand isa supposed to be able to replace slcan-attach functionalities. It's true except for the -l option.
Is there any reason why the listen-only functionality has not been implemented in slcand?

**Comment by hartkopp** [comment]
No - there is no special reason why slcand does not support the listen-only option. Up to now nobody complained about it :-)
If you are interested to have it supported feel free to send a patch.

**Comment by hartkopp** [comment]
Applied here:
https://github.com/linux-can/can-utils/commit/d82ccd76ac71ed2cd8e567495780994f766d1b9b
