### ISSUE TITLE
socket: Protocol not supported

### ISSUE THREAD

**Issue by ikuyas** [linux-can/can-utils#192]
When I execute isotpsniffer, it said "socket: Protocol not supported".
The function socket() at 279 in isotpsniffer.c has error. the return value "s" is -1.
What should I do to fix the problem?
I used isotpdump, but isotpsend didn't work as the same error with isotpsniffer. 
OS is ubuntu 18.04.3 LTS 64bit.

**Comment by hartkopp** [comment]
Did you compile & install the can-isotp module?
See README from https://github.com/hartkopp/can-isotp

**Comment by ikuyas** [comment]
> Did you compile & install the can-isotp module?
=> Thank you for your comment. 
I used isotpsniffer after installing can-isotp module.
