### ISSUE TITLE
"setsockopt: Invalid argument" at isotpsniffer

### ISSUE THREAD

**Issue by ikuyas** [linux-can/can-utils#193]
When I execute isotpsniffer, it said "setsockopt: Invalid argument".
The function setsockopt() at 325 in isotpsniffer.c has error. The return value is -1.
What should I do to fix the problem?
OS is ubuntu 18.04.3 LTS 64bit.

**Comment by hartkopp** [comment]
Many thanks for the report!

Fixed in https://github.com/linux-can/can-utils/commit/da65fdfe0d1986625ee00af0b56ae17ec132e700

**Comment by ikuyas** [comment]
Thank you for your quick fixing.
I used isotpsniffer without any error.
