### ISSUE TITLE
Android.mk out of date?

### ISSUE THREAD

**Issue by hartkopp** [linux-can/can-utils#202]
As Travis-CI recently detected a problem doing an Android NDK build I wondered why Android.mk had its last update in 2015 - while there have been several new tools (e.g. for j1939) added since then.
Is Android.mk still relevant? Should it been updated?

**Comment by gibsson** [comment]
For AOSP build, you'll have to switch to Android.bp (new format) at some point:
https://source.android.com/setup/build#androidbp_file_format
I don't really use NDK so I can't say for sure what's its requirement.

**Comment by hartkopp** [comment]
But how are you building your code right now? Does it build the J1939 stuff which has been added at last?

**Comment by gibsson** [comment]
I'm building the AOSP way, so either by defining the tools I want as part of `PRODUCT_PACKAGES` or by forcing the build as follows:
```
$ mmm external/can-utils/
```
And no j1939 isn't built as it hasn't been added to `Android.mk`.

**Comment by hartkopp** [comment]
Created pull request to fix this issue https://github.com/linux-can/can-utils/pull/215
