### ISSUE TITLE
Possible options bug in can-calc-bit-timing?

### ISSUE THREAD

**Issue by reportingsjr** [linux-can/can-utils#21]
Hi,
I was browsing though the can-calc-bit-timing code and notice that there is an argument parsing line with p when it appears that it should be a q based on the switch below it. Can someone verify?

https://github.com/linux-can/can-utils/blob/master/can-calc-bit-timing.c#L641

**Comment by marckleinebudde** [comment]
Thanks, fixed by https://github.com/linux-can/can-utils/commit/b70a76670dbe8925c2a7c75f90d36a28a8878d7a.
