### ISSUE TITLE
J1939 messages not sent/received in Ubuntu 20.04 (Kernel 5.4)

### ISSUE THREAD

**Issue by BalkanRising** [linux-can/can-utils#212]
Hi guys, hope all is well! I think I am facing an issue with the j1939 driver in kernel 5.4. The below test works with a very old set of j1939/can drivers on my arm board running kernel 4.9 but fails on Ubuntu 20.04 x86/Kernel 5.4:

**Terminal 1:**

`testj1939 -r vcan0`

**Terminal 2:**

`testj1939 -s8 vcan0:0x80 :0x12300`

**Problem:** In Ubuntu 20.04, Terminal one never prints anything out, indicating the message I sent from terminal 2 did not get properly sent or received. Before I start debugging the driver, I am wondering if there are any known issues with what I am trying to do? I did not see anything while looking through older issues on here.

**Setup**

Install Ubuntu 20.04 and can-utils and then do the following to set up machine:

```
modprobe vcan
sudo ip link add dev vcan0 type vcan
sudo ip link set up vcan0
modprobe can-j1939
```

**Comment by josemic** [comment]
Have you seen #159?

**Comment by BalkanRising** [comment]
Thank you to @josemic for pointing out issue #159. It looks like broadcast does not work and so when I changed the commands to the following it worked as expected:

**Terminal 1:**

testj1939 -r vcan0:0x69

**Terminal 2:**

testj1939 -s8 vcan0:0x70 vcan0:0x69,0x1200

According to @olerem in issue #159, broadcast not working is a defect with testj1939 utility:

> send to broadcast is currently not supported by testj1939

**I would like to point out broadcast also does not work in my C++ code either**. It looks like it is an issue with the J1939 driver in kernel 5.4. This functionality works in the older version of the driver I am using on my embedded system running kernel version 4.9. Can someone confirm if this is fixed or not? Should I close this issue?

**Comment by josemic** [comment]
I have closed #159, as all procedures described in [kickstart.md](https://github.com/linux-can/can-utils/blob/master/can-j1939-kickstart.md) now have passed on my Ubuntu 20.04 machine. 
However I have not used the latest can-utils package from ubuntu, instead I have compiled the can-utis myself. 
Please test again with self compiled can-utils from this repository.

**Comment by josemic** [comment]
@BalkanRising: Is this solved now? Can we close the issue?

**Comment by BalkanRising** [comment]
Yes, the core of my problems in my C++ code was that I needed to pass a socket option to enable broadcast, whereas in the earlier version of the driver that option was not required. If the latest can-utils works then I don't see any issue with the driver or testj1939.
