### ISSUE TITLE
j1939: make j1939spy capable displaying large packages

### ISSUE THREAD

**Issue by josemic** [linux-can/can-utils#218]
Currently the length variables len, pkt_len and j in 1939spy.c are integer size.
```
unsigned int len;
...
int pkt_len;
...
int ret, ... j,...;
...
ret = recvmsg(sock, &msg, 0);
...
for (j = 0; j < len; )
```
This limits the maximum size of packages, which can be sniffed.
Change len, pkt_len, j and ret to e.g. long. Are there any other changes needed?

**Comment by marckleinebudde** [comment]
The maximum ETP packet length is less than 112 MiB. That should fit into an `int` and an `unsigned int`.

**Comment by josemic** [comment]
You are right. My error. We can close this.
