### ISSUE TITLE
README.md add j1939 specific tools in overview

### ISSUE THREAD

**Issue by hartkopp** [linux-can/can-utils#235]
@olerem : Can you please add a small section that tells about the j1939 tools in one line here?
A reference to the can-j1939(-kickstart).md files at the end of this j1939 section would be cool too.
Thanks!

**Comment by olerem** [comment]
Done: https://github.com/linux-can/can-utils/pull/238

**Comment by hartkopp** [comment]
Thanks @olerem  - closing the issue ...
