### ISSUE TITLE
Why candump capture singals(SIGTERM,SIGUP,SIGINT)

### ISSUE THREAD

**Issue by oak-tree** [linux-can/can-utils#263]
Hey,

According to https://github.com/linux-can/can-utils/blob/c3d9cc2027d261dbde8b5fe6d82de87cd0ed5596/candump.c#L252
candump captures and cancel the following signals: `SIGTERM,SIGUP,SIGINT`
any specials reason it does so?

Thanks

**Comment by marckleinebudde** [comment]
Hey @oak-tree,

what do you mean by "cancel" a signal? These calls install a signal handler function called `sigterm`

https://github.com/linux-can/can-utils/blob/c3d9cc2027d261dbde8b5fe6d82de87cd0ed5596/candump.c#L163-L166

which is used to shut down the `while` loop in `main()`.

https://github.com/linux-can/can-utils/blob/c3d9cc2027d261dbde8b5fe6d82de87cd0ed5596/candump.c#L616

**Comment by oak-tree** [comment]
@marckleinebudde 
I Do not know how I missed that, the signals are there to cancel the infinity loop when needed.
Cool thanks
