### ISSUE TITLE
Candump no data?

### ISSUE THREAD

**Issue by johndoster56** [linux-can/can-utils#279]
I'm working with Ubuntu 20.04, arduino R3, seeduino V2 can bus shield. I've 'successfully' configured the device but cannot see data transmission. Can confirm data link operation and integrity/ activity with oscilloscope. I have successfully seen data under send/ receive terminals via vcan, but after attempting to implement on GMLAN in seeing nothing. Please advise as this has become a frustrating venture. 
![Screenshot from 2021-03-04 09-57-36](https://user-images.githubusercontent.com/73857242/110018490-f33e3b00-7cec-11eb-82e5-0cc99111bb58.png)
![Screenshot from 2021-03-04 09-59-09](https://user-images.githubusercontent.com/73857242/110018562-06e9a180-7ced-11eb-8a9c-02bddd859873.png)
![20210303_141327](https://user-images.githubusercontent.com/73857242/110018585-0bae5580-7ced-11eb-9516-d83da1f688ec.jpg)

**Comment by johndoster56** [comment]
After reviewing issue 170 I believe this applies in the arduino coding and has something to do with it
![Screenshot_20210304-133039_Chrome](https://user-images.githubusercontent.com/73857242/110019710-65fbe600-7cee-11eb-8825-198610671df8.jpg)

**Comment by hartkopp** [comment]
So this issue can be closed?

**Comment by johndoster56** [comment]
> So this issue can be closed?

I wouldn't say so. Not yet,  I read about it some last night,  will post more when time allows
