### ISSUE TITLE
J1939 how to get dst addr on recv side

### ISSUE THREAD

**Issue by swordjjjkkk** [linux-can/can-utils#307]
if A client  send J1939 package to B client,  how does B client know the dst addr is B's id or  0xff?

**Comment by olerem** [comment]
Hi, you can find more information here: https://www.kernel.org/doc/html/v5.5/networking/j1939.html#recvmsg-2

**Comment by swordjjjkkk** [comment]
> Hi, you can find more information here: https://www.kernel.org/doc/html/v5.5/networking/j1939.html#recvmsg-2

thank you very much. that is exactly what i need
