### ISSUE TITLE
get passive error when i manipulate CAN BUS

### ISSUE THREAD

**Issue by dzeko1234** [linux-can/can-utils#308]
Hello , I developed a Qt/C++ Application to send/receive data from a car control board .

when I run my application I get an error passive in the car control board .
 
But when I rerun my app many time it works perfectly .

Is this problem caused from my software ? 
How can i find it ? how can diagnosis this problem .

thank you

**Comment by marckleinebudde** [comment]
Error passive is an indicator that there is something not correct with the CAN bus. Make sure you have proper termination, At least 2 CAN stations on the CAN bus, everywhere the same bit rate. On the Linux side you can dump the bus using `candump any,0:0,#FFFFFFFF -extA`, this also decodes any errors detected by your local CAN controller (given the controller and driver support this).

For any automotive related questions, look on the internet for car hacker forums/mailing lists etc...
