### ISSUE TITLE
linking socketcan to swift app on raspbian buster?

### ISSUE THREAD

**Issue by leisurehound** [linux-can/can-utils#310]
not a can-utils issue per se, but has anyone successfully linked socketcan to a swift app on Raspbian (Buster)?

`    
    module CSocketCAN [system] {
    header "../../Headers/CSocketCAN-Bridging-Header.h"
    link “socketcan"
    export *
    }
`

where the Bridging header is simply:

`
    #import <linux/can.h>
    #import <linux/can/raw.h>
`

I can import the symbols into the swift app, but linking is causing problems with dispatch.  I imagine Swift's Foundation library is also importing libdispatch so it might be trying to link it twice?

`
    <unknown>:0: warning: missing submodule 'CDispatch'
    <unknown>:0: warning: missing submodule 'Dispatch'
`

Any thoughts on how to bring socketcan into Swift?  I've got what I want mostly working bridging to C for the socket/socketcan symbols and calls, but would prefer to stay in Swift directly with the socket functions (which swift already bridges) in Swift would be more convenient.

**Comment by marckleinebudde** [comment]
Hello @leisurehound,

```
<unknown>:0: warning: missing submodule 'CDispatch'
<unknown>:0: warning: missing submodule 'Dispatch'
````

this looks like a swift problem not a CAN problem. The main idea behind SocketCAN is to use the standard socket API so send and receive CAN frames. Please ask your fellow swift developer for help.
