### ISSUE TITLE
slcan_attach + slcand could not receive packets from serial connection

### ISSUE THREAD

**Issue by dannywi** [linux-can/can-utils#324]
I could send CAN messages using ```cansend```, but ```candump``` didn't receive anything. Could anybody please check what might be the problem here? Thank you.
* ```cansend``` worked fine, I could receive the CAN messages at the other end
* CAN messages sent from the other end didn't appear in ```candump```
* There's no RX packet received when I checked ```ifconfig``` (the counts below I guess were the acks from the ```cansend``` messages)
* if I connect directly to the device using ```minicom```, I could see messages incoming.
* Done on Raspberry Pi 4 ```5.10.63-v7l+ #1459 SMP Wed Oct 6 16:41:57 BST 2021 armv7l GNU/Linux```

```
    $ sudo slcan_attach -f -s6 -o /dev/ttyACM0
        attached tty /dev/ttyACM0 to netdevice slcan0
    $ sudo slcand -S 115200 ttyACM0 slcan0
    $ sudo ip link set up slcan0
    $ ifconfig
slcan0: flags=193<UP,RUNNING,NOARP>  mtu 16
        unspec 00-00-00-00-00-00-00-00-00-00-00-00-00-00-00-00  txqueuelen 10  (UNSPEC)
        RX packets 1  bytes 8 (8.0 B)
        RX errors 0  dropped 0  overruns 0  frame 0
        TX packets 0  bytes 0 (0.0 B)
        TX errors 0  dropped 0 overruns 0  carrier 0  collisions 0
    $ ./cansend slcan0 123#AABBCCDD
    $ ifconfig
slcan0: flags=193<UP,RUNNING,NOARP>  mtu 16
        unspec 00-00-00-00-00-00-00-00-00-00-00-00-00-00-00-00  txqueuelen 10  (UNSPEC)
        RX packets 2  bytes 16 (16.0 B)
        RX errors 0  dropped 0  overruns 0  frame 0
        TX packets 1  bytes 4 (4.0 B)
        TX errors 0  dropped 0 overruns 0  carrier 0  collisions 0
```

Switching to ```minicom```
```
    $ sudo ifconfig slcan0 down
    $ sudo killall slcand
    $ minicom -b 115200 -D /dev/ttyACM0

Welcome to minicom 2.8
OPTIONS: I18n
Port /dev/ttyACM0, 11:00:33
Press CTRL-A Z for help on special keys

t2A18DEADBEEFCAFEBABE
T1234BEEF8DECAF00011223344
t2A18DEADBEEFCAFEBABE
```

**Comment by hartkopp** [comment]
> ```
>     $ sudo slcan_attach -f -s6 -o /dev/ttyACM0
>         attached tty /dev/ttyACM0 to netdevice slcan0
>     $ sudo slcand -S 115200 ttyACM0 slcan0

IIRC `slcan_attach` is the (testing) tool to attach the line discipline 'by hand' and `slcand` does that job as a service.

You should either use `slcand` OR `slcan_attach`

**Comment by dannywi** [comment]
Thank you for the prompt response! I tried using ```slcand``` only, and still got the same result, i.e. ```cansend``` worked, ```candump``` output nothing, though I could confirm the incoming serial data with raw ```minicom```.

```
$ sudo slcand -S 115200 -s6 ttyUSB0 can3
$ sudo ip link set can3 up
$ ifconfig can3
can3: flags=193<UP,RUNNING,NOARP>  mtu 16
        unspec 00-00-00-00-00-00-00-00-00-00-00-00-00-00-00-00  txqueuelen 10  (UNSPEC)
        RX packets 1  bytes 8 (8.0 B)
        RX errors 0  dropped 1  overruns 0  frame 0
        TX packets 0  bytes 0 (0.0 B)
        TX errors 0  dropped 0 overruns 0  carrier 0  collisions 0

# this didn't output anything
$ candump can3

# this sent the frame across successfully
$ cansend can3 345#abdc

$ ifconfig can3
can3: flags=193<UP,RUNNING,NOARP>  mtu 16
        unspec 00-00-00-00-00-00-00-00-00-00-00-00-00-00-00-00  txqueuelen 10  (UNSPEC)
        RX packets 2  bytes 16 (16.0 B)
        RX errors 0  dropped 1  overruns 0  frame 0
        TX packets 1  bytes 2 (2.0 B)
        TX errors 0  dropped 0 overruns 0  carrier 0  collisions 0
```

I've compiled the repository, any pointer on where I should start looking into? Thank you.

**Comment by hartkopp** [comment]
I had to get my own CANUSB adapter to check whether slcan works in general. And it does ;-)

Using `slcand -o -c -f -s6 -F /dev/ttyUSB0` I can see the slcand status information - and everything looked good.
Then `ifconfig slcan0 up` (ip link is even better). And from  that point a 500kbit/s CAN stream worked in both directions.

I think you simply missed `-o -c -f` when calling `slcand`, right?

**Comment by dannywi** [comment]
Thanks a lot for taking the trouble! I tried ```sudo slcand -o -c -f -S 115200 -s6 -F /dev/ttyUSB0``` but the problem persisted. What I find confusing are:
- ```cansend``` works totally fine, but ```candump``` doesn't
- if I directly connect to the tty device using ```minicom``` I could receive the serial feeds of the CAN frames I sent like below, but the ```ifconfig```'s ```RX packets``` count didn't increase at all.
```
    t2A18DEAD07EFCAFEBABE
    T1234BEEF8DECAF02B11223344
    ... and so on ...
```
Most probably the problem is local here and I'm trying to track it. Any pointer on what I can check next would be much appreciated!

**Comment by yegorich** [comment]
@dannywi just curious, what kind of USB-to-CAN adapter you are using? Our USB-CAN Plus devices require hardware handshake on the serial line. Hence, I start it like this:

`slcand -o -s8 -t hw -S 3000000 /dev/ttyUSB0`

For more details, look here: https://github.com/visionsystemsgmbh/programming_examples/tree/master/CAN/c/socketcan

**Comment by dannywi** [comment]
@yegorich , thanks for looking into this. I tried ```-t hw``` and ```-t sw```, but ```candump``` still output nothing. I have 2 devices:
- Arduino UNO + Seeed CAN-BUS Shield V1.2 (like [this](https://www.amazon.co.jp/-/en/SeeedStudio-_-CAN-BUS-Shield-V1-4-2/dp/B074PPYXGR/ref=sr_1_2?keywords=seeed+can%E3%83%90%E3%82%B9%E3%82%B7%E3%83%BC%E3%83%AB%E3%83%89&qid=1639191092&sr=8-2) one)
- Arduino Nano + MCP2515/TJA1050 (like [this](https://www.amazon.co.jp/gp/product/B08R5FQLH3/ref=ppx_yo_dt_b_asin_title_o08_s00?ie=UTF8&psc=1) one)

using this [library](https://github.com/kahiroka/slcanuino). Though I forked it [here](https://github.com/dannywi/slcanuino_pio) to modify some things, but the main I/O logic is not touched.

As I can see the incoming streams through direct connection to the tty serial port (when I don't attach it to a netdevice), and  the fact that ```cansend``` and ```cangen``` work, I assumed that the issue wasn't in the hardware, but please correct me if the assumption is not good.

Thank you.

**Comment by hartkopp** [comment]
I'm not sure about `Serial.println(buf);` here:

https://github.com/dannywi/slcanuino_pio/blob/main/src/main.cpp#L179

Shouldn't it be `Serial.print(buf);` ??

At least I would look for something at the line end.

**Comment by dannywi** [comment]
You're right @hartkopp, ```Serial.println``` was the problem, changing it to ```Serial.print``` solved it! Now ```candump``` works perfectly here.

I couldn't find in ```slcand.c``` or ```candump.c``` how the extra ```\r\n``` from ```println``` would cause problem though, but I guess that's just me not being familiar enough with linux line discipline.

Anyhow, I'm really grateful for this, thanks a lot for the helps!

**Comment by hartkopp** [comment]
I'm happy that it works now!
Btw. the code for slcan is in the Linux CAN drivers inside the kernel:
https://github.com/torvalds/linux/blob/master/drivers/net/can/slcan.c

And I was not able to see an issue there, why an additional `\r\n` should cause a problem ?!?!? o_O

At least it was very helpful that you were able to provide your code for a review ;-)

**Comment by dannywi** [comment]
Ah, so there it is! But I couldn't find anything obvious by just eye-balling the codes, and I don't have the resource to debug the kernel at the moment. I'll close the issue for now (hope this is the right protocol). Many thanks for the cooperation and enlightening replies!

**Comment by n2j7** [comment]
For future readers, maybe helpfull.
This situation can happen if your USB-CAN adapter send wrong-formatted frame, like `t111311233` (it's hard to detect by eyes, but there are missing part for second byte, the right one is `t1113112233`)

In this situation slcand (or slcan_attach) won't send any byte to netdevice (slcan0). So the problem is at slcand side or at your device side

**Comment by marckleinebudde** [comment]
Does the RX dropped counter increase if a wrong-formatted frame is send?

**Comment by n2j7** [comment]
> Does the RX dropped counter increase if a wrong-formatted frame is received?

No, `slcand` will not send this frame into can network interface, so running `candump -e -x slcan0` add no additional info

**Comment by marckleinebudde** [comment]
I mean the RX dropped counter in the interface statistics shown by `ip --details -s -s -s link show can0`.

**Comment by n2j7** [comment]
nope
```
$ ip --details -s -s -s link show can0
160: can0: <NOARP,UP,LOWER_UP> mtu 16 qdisc pfifo_fast state UNKNOWN mode DEFAULT group default qlen 10
    link/can  promiscuity 0 minmtu 0 maxmtu 0 numtxqueues 1 numrxqueues 1 gso_max_size 65536 gso_max_segs 65535 
    RX: bytes  packets  errors  dropped overrun mcast   
    0          0        0       0       679     0       
    RX errors: length   crc     frame   fifo    missed
               0        0       0       0       0       
    TX: bytes  packets  errors  dropped carrier collsns 
    0          0        0       0       0       0       
    TX errors: aborted  fifo   window heartbeat transns
               0        0       0       0       0       

```
my uc task is looking like that
```
static void twai_transmit_task(void* arg) {
	while (1) {
		if (millis() - prevTX >= 750) {
			// wakeup
			Serial.print("t111311233\r");// @DEBUG CANDUMP test
			prevTX = millis();
		}
		vTaskDelay(pdMS_TO_TICKS(10));
	}
	vTaskDelete(NULL);
}
```

**Comment by marckleinebudde** [comment]
What about the `overrun` counter? Does it increase?

**Comment by n2j7** [comment]
> What about the `overrun` counter? Does it increase?

sorry, but, what is that and how to view it?

**Comment by n2j7** [comment]
oh, I see, yeah, it increases

**Comment by ashwinsushil** [comment]
Hi @hartkopp everyone, I ran into a similar issue while using [these](https://www.antratek.be/usb-can-analyzer?gad_source=1&gclid=CjwKCAjwlbu2BhA3EiwA3yXyu0uDZjVVWESEb0WP5Tn8BBOzZPVOh5mGJ6WPs9hDhzxQyg6nOiQqLxoCYn4QAvD_BwE) devices. 

I have connected a CAN encoder to this USB-CAN analyser, to see the data from the encoder on `candump`. Following this repo https://github.com/kobolt/usb-can/tree/master. I was able to set a heartbeat and even view the traffic. So I confirmed that the device is working. I can even see the green light of the CAN analyzer blinking indicating that there is reception.

![image](https://github.com/user-attachments/assets/2f51c994-3250-4f42-b3cf-42d11c6d1ec8)

But the trouble comes when I try to set up the interface using `slcand`.  There is no data on `candump` nor there is any traffic on the `slcan0` interface.

![image](https://github.com/user-attachments/assets/4a3e9772-652c-49cf-9d25-355075178896)

Do you have any tips that you can share that I might have missed?

**Comment by marckleinebudde** [comment]
I think this device is not compatible with the `slcan` protocol.

**Comment by ashwinsushil** [comment]
@marckleinebudde Thanks for the super quick reply. Maybe this is a bad place to ask this, but do you have any other alternative to  `slcan`  for this device if you are familiar?

**Comment by ashwinsushil** [comment]
@marckleinebudde Got it thank you. :)

**Comment by hartkopp** [comment]
@marckleinebudde if you take a look at the firmware of the kobolt project here:
https://github.com/Kosmonova/usb-can-firmware-stm32
it looks like they are using a bluepill_f103c6 where the https://github.com/candle-usb/candleLight_fw README states that the STM32F103 will NOT work with the candleLight FW.
Hm - IMHO the best would be to flash the bluepill_f103c6  with the excellent candleLight FW.
Obviously using USB and CAN together with the bluepill_f103c6  seems to work, right?

**Comment by marckleinebudde** [comment]
> Obviously using USB and CAN together with the bluepill_f103c6 seems to work, right?

Maybe there's a dedicated USB-to-serial chip on this device, according to
https://github.com/kobolt/usb-can/blob/aabba66a5526928375e4ac77f7fad56c6181c451/README.md?plain=1#L10 the device identifies itself in USB as:
```
Bus 002 Device 006: ID 1a86:7523 QinHeng Electronics HL-340 USB-Serial adapter
```
and the firmware indicated the STM writes to UART: https://github.com/Kosmonova/usb-can-firmware-stm32/blob/51bd0b198e3db8572b190be969d6a827173958f5/Core/Src/main.c#L117

**Comment by hartkopp** [comment]
Ah, ok! Thanks for the pointers. Then this adapter is definitely not capable to run the candeLight firmware!
The only thing could be to create a "standard SLCAN" protocol as an alternative kobolt firmware - for masochist developers only :-D
Getting a candleLight compatible hardware and flash the latest candleLight firmware is definitely the better approach.
Thanks @marckleinebudde  !
