### ISSUE TITLE
What does "-i" mean in cangw options ? 

### ISSUE THREAD

**Issue by nico0481** [linux-can/can-utils#337]
Hello, what is the meaning of '-i' in cangw options  list?(allow route...)

Thank you

**Comment by hartkopp** [comment]
You usually do not want a CAN frame that was received from e.g. `can0` can be sent back after (some) modifications to the same interface (and is then probably processed again and again). If you really have a use-case that needs to send a CAN frame on the originating CAN interface you can override this protection with `-i`

**Comment by nico0481** [comment]
Ok 
Thank you
