### ISSUE TITLE
Filter in canplayer

### ISSUE THREAD

**Issue by nico0481** [linux-can/can-utils#338]
Hello,

It could be interesting to implement filter and mask (XXX:YYY) in canplayer. To replay only allowed frame from a log.

Thank you
Regards
Nico

**Comment by hartkopp** [comment]
The filters from `candump` are simply forwarded to the Linus kernel CAN_RAW filters. So I assume this to be pretty complex to implement in `canplayer` - especially in conjunction with the netdevice interface assignment feature.

Have you considered to use `grep` or `grep -v` on the logfiles to get a specific excerpt of CAN IDs? The `grep` approach would maintain the timestamps and the interface name too.

**Comment by nico0481** [comment]
OK
Thanks
