### ISSUE TITLE
Clarification on ifaddrs struct address specific data (ifa_data) content

### ISSUE THREAD

**Issue by derek-will** [linux-can/can-utils#358]
When I invoke `getifaddrs` the `ifaddrs` struct that is returned has a non-null `ifa_data` field, but I don't know what `ifa_data` is pointing to.

According to the [documentation](https://www.man7.org/linux/man-pages/man3/getifaddrs.3.html):

> The ifa_data field points to a buffer containing address-family-specific data; this field may be NULL if there is no such data for this interface.

How to interpret this data?

**Comment by hartkopp** [comment]
From what I've read it should be a `struct sockaddr` - for CAN devices likely `struct sockaddr_can`

But I haven't tested it on my own.
