### ISSUE TITLE
cansend command problem

### ISSUE THREAD

**Issue by amolina-chargevite** [linux-can/can-utils#360]
Hi,

I am using the `cansend` command and it works correctly the first time that I execute it, but if I want send several messages it doesn't works. For example I use: `cansend can0 163#12345678` and in the bus is sended periodically this message, but if after I execute others message such as for example: `cansend can0 333#12345678` this doesn't works, in the bus continue the previous message. Which is the problem? Is it problem of my bus configuration or is problem of the library?

Thanks in advance.

**Comment by marckleinebudde** [comment]
Any news on this? Feel free to re-open.
