### ISSUE TITLE
WSL2-linux-kernel can-subsystems not found in configuration

### ISSUE THREAD

**Issue by ursincantieni** [linux-can/can-utils#364]
Hi, I want to make use of SocketCAN on windows, therefore I'm trying to compile a WSL2-Linux Kernel, Ubuntu 20.04 based.
I'm following [these instructions](https://unix.stackexchange.com/questions/594470/wsl-2-does-not-have-lib-modules) (bottommost reply). Problem is, when running `$ make menuconfig`, the `Networking suppo
rt` submenu is empty, no can related stuff to find.

Any help is appreciated!

**Comment by hartkopp** [comment]
I followed these instructions (which is similar to your reference):

https://gist.github.com/cerebrate/d40c89d3fa89594e1b1538b2ce9d2720

But I built my own WSL2 Kernel completely WITHOUT modules and compiled the CAN networking and driver stuff INTO the Kernel zImage which worked for me. So selecting "Y" instead of "M" in menuconfig.

**Comment by ursincantieni** [comment]
I see, thanks for the help, that worked.

However, as soon as I get to `modprobe vcan`, I keep getting 
`modprobe: FATAL: Module vcan not found in directory /lib/modules/4.4.0-22000-Microsoft`,
which is unfortunate as this is what I'm trying to fix.

My menuconfig looks like as shown in the screens. Any idea what might be causing this?

![image](https://user-images.githubusercontent.com/62484225/173153247-e1e96564-3d22-48c5-acff-d0d412b9b15a.png)
![image](https://user-images.githubusercontent.com/62484225/173154862-673a5762-2a85-4dbe-9327-06a7db2a462e.png)
![image](https://user-images.githubusercontent.com/62484225/173154895-6f6a9f91-9b68-4ad6-ada9-f01727e3da8b.png)

**Comment by hartkopp** [comment]
That is a correct behavior.

You can't `modprobe` a vcan module as it is no module anymore (when it is built-in).

You can directly start with creating a virtual CAN interface with `ip link add type vcan`.
