### ISSUE TITLE
candump can0 does not show data

### ISSUE THREAD

**Issue by ColorCorw** [linux-can/can-utils#409]
I have a computer(ubuntu 20) with CAN interface,and now I need to do CAN interface related development. 
the command lines:
terminal1:
```
ifconifg (can0 is displayed)
sudo ip link set can0 type can bitrate 500000
sudo ip link set up can0
```

terminal2:
```
candump can0
```

terminal1:
```
cansend can0 123#1122334455667788
```

However, the second terminal has no data output.

I tried using a virtual CAN interface.
the command lines:
terminal1:
```
sudo modprobe vcan
sudo ip link add dev vcan0 type vcan
ifconifg (vcan0 is displayed)
sudo ip link set up vcan0
```

terminal2: 
```
candump vcan0
```

terminal1:
```
cansend vcan0 123#1122334455667788
```

The second terminal outputs the data

Can anyone help with this？
Kind regards

**Comment by hartkopp** [comment]
To have a "happy CAN bus" you need at least TWO CAN bus nodes connected to each other - with an identical bitrate setting and a termination of 2 x 120 Ohms on each side of the CAN bus (= 60 Ohms total).

There is no acknowledge generated by a receiving node and therefore the sending node can not successfully send that CAN frame -> no output in candump ;-)

**Comment by ColorCorw** [comment]
the problem was solved, thank you very much
