### ISSUE TITLE
canlogserver: does it log CAN frame from a remote?

### ISSUE THREAD

**Issue by yashi** [linux-can/can-utils#421]
README.md states that
> canlogserver : log CAN frames from a remote/local host

But does it log frames from a remote?  I've been reading the source code but it only `write()`s to `accsocket`, which is the return value of `accept()`.

It does of cause call `socket(PF_CAN, ...)` and `recvfrom()` on the interfaces given.  But does it qualified as a remote? What am I missing?

**Comment by marckleinebudde** [comment]
I think your analysis is correct. It was @hartkopp, who has written that part of the README :)

**Comment by hartkopp** [comment]
Hi @yashi ,
yes, your description fits better to the use-case!
I will add some remarks on the PR
