### ISSUE TITLE
Mcp2515 And Raspiberry Pi 4B

### ISSUE THREAD

**Issue by fy8207345** [linux-can/can-utils#427]
I have a mcp2515 module and Raspiberry Pi 4B. And I installed the can-utils. Is there A Circuit between the Mcp2515 and Raspberry GPIOs? Thanks.

**Comment by AndreiCherniaev** [comment]
> 



> Mcp2515 and Raspberry GPIOs?

Take [it](https://github.com/linux-can/can-utils/issues/427#issue-1684217025)

**Comment by arturca** [comment]
If by MCP2515 module you mean PCB that is SPI to CAN interface, which includes MCP2515 (its just a Stand-Alone CAN Controller with SPI Interface - google it) and TJA1050 (5V CAN transiver) you still need to make one adjustment that is described here:
https://forums.raspberrypi.com//viewtopic.php?t=141052.
But if you actually mean the MCP2515 CAN controller module, you can figure out connections based on this link.

**Comment by marckleinebudde** [comment]
Seems to be solved, I'll close this issue.
