### ISSUE TITLE
Repeated transmission of can frames (within a while loop) is not working

### ISSUE THREAD

**Issue by anandbhavi** [linux-can/can-utils#431]
Hi Team,

We are using Linux mcp 251xfd kernel driver on Xilinx SOC XAZU3 based SOC  . The frames are sent from mcp chip on our board (mcp chip 2517fd connected to our SOC via SPI controller )  to CANananlyser node and can frames can be seen on CAnanalyser software connected to windows pc;

We are observing that after 4 times of sending the frames, we dont see any more frames on CAN Analyser software.

Please find the can user space application attached and Screen shots of CANAnalyser pro attached;
also attached are our system.dts .

Please let us know how to debug this issue;; Thanks in Advance

mcp kernel drivers link
https://github.com/Xilinx/linux-xlnx/tree/xlnx_rebase_v5.10/drivers/net/can/spi/mcp251xfd

[mcp_atatchments.zip](https://github.com/linux-can/can-utils/files/11483211/mcp_atatchments.zip)

**Comment by anandbhavi** [comment]
![ip_stats](https://github.com/linux-can/can-utils/assets/69208942/734c3b0c-50e7-4982-9f7b-a51e6860a5b8)
Attaching the ip link stats; The count of Tx Bytes is not increasing inspite of transmission working 4 times .Please let us know the reason:

**Comment by anandbhavi** [comment]
Hi Team,
We have already tested the mcp chip on Xilinx SDK where  in we don't have linux drivers. These mcp drivers are provided by Microchip and are part of Xilinx SDK ; Here we dont see this issue of transmission stopping after 4 times; Please note this point

**Comment by marckleinebudde** [comment]
- Can you provide the device tree source?
- Can you receive CAN frames?
- What's the output of `cat /proc/interrupts` before and after you've send a single CAN frame?

**Comment by marckleinebudde** [comment]
The IRQs of interest is not only the `ff040000.spi`, but also the `spi1.0`. The `ff040000.spi` is the SPI host controller, that is triggered for SPI transfers, the `spi1.0` is the IRQ from the mcp251xfd to the SoC.

According to you attached file `spi1.0` stays 0. This means the IRQ line is not connected, or misconfigured in your DT. Have a look at the bindings [example](https://elixir.bootlin.com/linux/v6.3/source/Documentation/devicetree/bindings/net/can/microchip,mcp251xfd.yaml#L60) how to configure it.

* use `IRQ_TYPE_LEVEL_LOW` not `IRQ_TYPE_EDGE_FALLING`
* double check that `&gpio 0x10` is the correct IRQ
* don't use `microchip,rx-int-gpios` while testing
* `clock-names` are not used, remove

It should look like this:

```
&spi0 {
	status = "okay";

	can@2 {
		compatible = "microchip,mcp2517fd";
		reg = <0>;
		clocks = <&can_osc>;
		interrupts-extended = <&gpio 0x10 IRQ_TYPE_LEVEL_LOW>;
		//microchip,rx-int-gpios = <&gpio 39 GPIO_ACTIVE_LOW>;
		spi-max-frequency = <20000000>;
	};
};
```

BTW: You will not have much fun with the mcp2517fd, that chip is quite broken, further the driver in the v5.10 kernel is quite old and slow.

**Comment by anandbhavi** [comment]
Thanks for your reply !

We used the above mentioned DT snippet in our system-user.dtsi ; 
Unfortunately there is no progress Marc;

;We also verified the &gpio 0x10 is the correct IRQ; Attached is the pic of UG 1085 document pic for zynq MP SOC;
we have to subtract 32 from 48 which gives hex 0x10 as the Hardware irq number which is given for the request irq API;
Please see S1 pic;

But Still we see spi1.0 interrupts as zero;  I believe you are mentioning that IRQ line should be asserted atleast for Tx interrupt since we commented microchip,rx-int-gpios ; let us know;
(Please see S2 pic ) ; 

Other Observations:

1) We observed that mcp251xfd_start_xmit function is called 4 times for our 4 invocations of our user space application (we put print in mcp251xfd_start_xmit function) and for further invocations of user space function mcp251xfd_start_xmit  is not getting called; This is strange considering that we can see error free 4  frames on cananylser window;
/
2)  Does it indicate we have missed  setting any socket options on this net socket or any issues with Socket net CAN framework which we missed;

This is high priority task ; 
Please give us any pointers to proceed further Marc;


[latest.zip](https://github.com/linux-can/can-utils/files/11503504/latest.zip)

**Comment by anandbhavi** [comment]
Hi Marc,

Thanks for Your reply; I would like to go for Commercial Support;
Please let me know further details;

-Regards
Anand B

**Comment by marckleinebudde** [comment]
Please contact sales@pengutronix.de

**Comment by anandbhavi** [comment]
Marc;

We could resolve the gpio issue with correct entries in dtsi file. We are
receiving mcp interrupts on our soc.

And our user space application is working as expected.

Thank you.

Another doubt:
We have 2 mcps on our board. On one of the mcp we see cerrif handler
getting generated at the first transmission from soc to mcp itself .the
berr counter is 128 and further communication stops.

we dont have any issues eith another mcp with linux driver..the transmit
and receive hanflers are getting  executed properly  .And also,
the baremetal drivers are executing properly on both mcps .

Let us know your thoughts.

Thank you

Regards Anand

**Comment by marckleinebudde** [comment]
> We have 2 mcps on our board. On one of the mcp we see cerrif handler
getting generated at the first transmission from soc to mcp itself .the
berr counter is 128 and further communication stops.

There's a problem with the CAN transceiver or on the CAN bus, i.e. transceiver not powered, rx/tx swapped, not attached to the CAN bus, wrong bit rate, no/wrong termination, no 2nd system on the CAN bus.

**Comment by anandbhavi** [comment]
Hi Marc,

All our issues have been addressed  internally.
There is no need of Commercial Support as of Now. 
Thanks again for your timely Support . 

I will close this Issue.

regards
Anand B
