### ISSUE TITLE
CAN remote frame with DLC greater than 8

### ISSUE THREAD

**Issue by a-matos00** [linux-can/can-utils#437]
Is it possible to send a remote request frame with a DLC greater than 8 by using cansend ?  I noticed that this is currently not implemented. When I send a remote request with dlc 12 from my windows application, candump reports a RTR frame with dlc 8.

**Comment by hartkopp** [comment]
Oh!
There really seems to be an issue with `cansend` ... I'll take a look at it.

But regarding `candump` -> please try the `-8` option, e.g. `candump -8 can0` to see those DLCs with `candump`.
`candump -L can0` prints the logfile format whoch also includes DLC > 8 stuff.

**Comment by hartkopp** [comment]
@a-matos00 can this issue considered to be solved for you?

**Comment by a-matos00** [comment]
Thank you so much for this information. This solves the issue then.
