### ISSUE TITLE
J1939 frame with length > 8 bytes not send

### ISSUE THREAD

**Issue by in-text** [linux-can/can-utils#441]
Hello! I've try to use J1939 with utility testj1939 according to [this](https://github.com/linux-can/can-utils/blob/master/can-j1939-kickstart.md) manual. When I try to send frame, which length more than 8 bytes, on the receive-side I have nothing.

Device 1:
```shell
testj1939 -s128 can0:0x80 can0:0x70,0xff01
```

Device 2:
```shell
testj1939 -r can0:0x70
```

Nothing on the device 2...

But when I've try this:
Device 1:
```shell
testj1939 -s8 can0:0x80 can0:0x70,0xff01
```

Device 2:
```shell
testj1939 -r can0:0x70
```

On the device 2 I have:
```
80 0ff01: 01 23 45 67 89 ab cd ef
```

And one strange thing: if I use `candump -L can0` (as replace to `testj1939 -r can0:0x70`) for traffic capture, I've see J1939 payload bytes in console...
Device 1:
```shell
testj1939 -r can0:0x70 &
testj1939 -s128 can0:0x80 can0:0x70,0xff01
```

Device 2:
```
root@dev:~# candump -L can0
(1688991773.508381) can0 18EC7080#108000131301FF00
(1688991773.509003) can0 18EC8070#111301FFFF01FF00
(1688991773.509623) can0 18EB7080#010123456789ABCD
(1688991773.510195) can0 18EB7080#02EF0123456789AB
(1688991773.510731) can0 18EB7080#03CDEF0123456789
(1688991773.511305) can0 18EB7080#04ABCDEF01234567
(1688991773.511876) can0 18EB7080#0589ABCDEF012345
(1688991773.512426) can0 18EB7080#066789ABCDEF0123
(1688991773.512974) can0 18EB7080#07456789ABCDEF01
(1688991773.513527) can0 18EB7080#0823456789ABCDEF
(1688991773.514078) can0 18EB7080#090123456789ABCD
(1688991773.514622) can0 18EB7080#0AEF0123456789AB
(1688991773.515174) can0 18EB7080#0BCDEF0123456789
(1688991773.529715) can0 18EB7080#0CABCDEF01234567
(1688991773.530260) can0 18EB7080#0D89ABCDEF012345
(1688991773.530810) can0 18EB7080#0E6789ABCDEF0123
(1688991773.531362) can0 18EB7080#0F456789ABCDEF01
(1688991773.531915) can0 18EB7080#1023456789ABCDEF
(1688991773.532459) can0 18EB7080#110123456789ABCD
(1688991773.533231) can0 18EB7080#12EF0123456789AB
(1688991773.533821) can0 18EB7080#13CDEFFFFFFFFFFF
(1688991773.534443) can0 18EC8070#13800013FF01FF00
```

In UART0 (dmesg) console I've see errors:
```
[ 309.320593] j1939xtp_rx_abort 2, 0ff01
[ 564.779835] j1939tp_rxtask: timeout on 2
```

When I've try to use vcan iface on the same device, I've faced with the same issue.

My env:
Linux Kernel 4.9.124 with kurt-vd linux kernel 4.9.10 j1939-can [backport](https://github.com/kurt-vd/linux/tree/j1939d-v4.9.10)

**Comment by marckleinebudde** [comment]
Sorry - that kernel is too. J1939 went mainline with v5.4, please use at least that version.

**Comment by in-text** [comment]
> Sorry - that kernel is too. J1939 went mainline with v5.4, please use at least that version.

I've use kurt-vd [backport](https://github.com/kurt-vd/linux/tree/j1939d-v4.9.10) with j1939-can support on older kernels.

**Comment by marckleinebudde** [comment]
I understand that you use Kurt's kernel, but there is no support for that old version, please use at least v5.4

**Comment by in-text** [comment]
> I understand that you use Kurt's kernel, but there is no support for that old version, please use at least v5.4.

Okay, but this may be difficult for me. I can't update kernel from 4.9 to 5.4, because some proprietary software, which I use, don't work on more fresh kernels (its shipped for me in binary form, developer of this software don't support it a long time).

Maybe exists some patch to the Kurt backport, which resolve my issue? As can I understand, on physical layer and on CAN_RAW layer all right (`candump -L can0` show frames (over 8 bytes length), which was send from second device).

Thanks

**Comment by marckleinebudde** [comment]
As there's no official support for the kernel you are using, you have to do it yourself or find someone else to do it for you: Here's a list of the patches on j1939 on the latest v5.4 kernel:
https://git.kernel.org/pub/scm/linux/kernel/git/stable/linux.git/log/net/can/j1939?h=v5.4.249

**Comment by olerem** [comment]
> > Sorry - that kernel is too. J1939 went mainline with v5.4, please use at least that version.
> 
> I've use kurt-vd [backport](https://github.com/kurt-vd/linux/tree/j1939d-v4.9.10) with j1939-can support on older kernels.

This version is not compatible to the version which was mainlined. User space applications are not quaranted to work with not mainlined version.
