### ISSUE TITLE
cansequence: negative errno bug

### ISSUE THREAD

**Issue by adienakhmad** [linux-can/can-utils#448]
Hi,

In `cansequence.c` I found the following line

https://github.com/linux-can/can-utils/blob/79601bd1d40110f0cfde90730fdb43dd4e2eb838/cansequence.c#L226

since `errno` cannot be a negative, checking against `-EINTR` will always evaluate to true and the program will exit instead of retrying write.

**Comment by adienakhmad** [comment]
It also seems even if the `poll` succeeded, it wouldn't retry the failed write.

**Comment by hartkopp** [comment]
You are right!  `-EINTR` should be `EINTR` .

Would you like to send a pull request with the fix?
