### ISSUE TITLE
Is it possible to send statically addressed J1939 messages to a can bus with just one active node?

### ISSUE THREAD

**Issue by mdeneen** [linux-can/can-utils#477]
This may be more of a can-j1939 module question, but is it possible to run something like j1931acd on a can bus with just one active node?  Whenever I attempt this with my setup j1939acd hangs, briefly, on socket close and the following lines appear in the kernel ring buffer:

can_put_echo_skb: BUG! echo_skb 0 is occupied!
j1939_tp_rxtimer: 0x534be15f: Timeout. Failed to send simple message.

The network at this time is comprised of two nodes; one is an ECU and the other is my Linux device.  It is properly terminated.

If I start a socketcan-based program which claims an address, j1939acd works as expected.  That is, it handles address claims and such in userspace and not in the kernel driver.  It feels like the kernel driver is expecting a response from someone.

**Comment by olerem** [comment]
Kernel already supports feedback over socket error queue. Current j1939acd is not using it.
Here is an example of code actually using this kind of feedback:
https://github.com/olerem/can-utils/blob/isobusfs-2023.11.03/isobusfs/isobusfs_srv_cm_fss.c#L105
