### ISSUE TITLE
cangw setup wrong

### ISSUE THREAD

**Issue by nico0481** [linux-can/can-utils#478]
Hello,

I managed to use previously cangw on physical interfaces (can0&can1)with for instance:
```
        sudo modprobe can-gw
        sudo cangw -A -s can0 -d can1
        sudo cangw -A -s can1 -d can0
```
rules are listed correctly

and then previously using:
```
        candump -t d -c -d -a -e -x -s 1 can1 -B can0
```

But now the 'B' or 'b' option seems no longer needed, but can interfaces are not forwarded to each other.
How can I set bridging between interfaces?
What's wrong with my set up?
Regards

**Comment by marckleinebudde** [comment]
`candump` doesn't have a `-B` option. What should it do?

**Comment by hartkopp** [comment]
> I managed to use previously cangw on physical interfaces (can0&can1)with for instance:
> 
> ```
>         sudo modprobe can-gw
>         sudo cangw -A -s can0 -d can1
>         sudo cangw -A -s can1 -d can0
> ```
> 
> but can interfaces are not forwarded to each other. How can I set bridging between interfaces? What's wrong with my set up? 

The setup is correct - but you likely do not see the outgoing traffic on your local machine as you did not enable the `-e` option to echo the sent traffic.

To have the `-B can1` functionality invoke `sudo cangw -A -s can0 -d can1 -e` 

Please also take a look what `cangw -L` tells you about the current can-gw routing jobs.

**Comment by nico0481** [comment]
it works now, it was HW issue
Thanks

**Comment by hartkopp** [comment]
Thanks!
