### ISSUE TITLE
Help me with data padding

### ISSUE THREAD

**Issue by hungcuiga1** [linux-can/can-utils#484]
Dear Develop team,
I am a newbie in C++ and I want to send data to can. I use ```iostpsend``` and see data is padding like I posted here https://stackoverflow.com/questions/77635005/padding-stdvectoruint8-t-in-embedded-c
I see this code over a week and I still can not understand where you do this future. Can you help me with that question? Thank you so much.

**Comment by marckleinebudde** [comment]
The ISO-TP is implemented in the Linux Kernel, the padding is added there.

What is your actual task?

**Comment by hungcuiga1** [comment]
Dear @marckleinebudde ,
Thank for your reply, I do not understand how this data is padded, I see option -p but I can not know what is follow code(how to it run). In https://stackoverflow.com/questions/77635005/padding-stdvectoruint8-t-in-embedded-c is my task. Sorry for my english. Thank you!

**Comment by hartkopp** [comment]
So you want an example to configure the Linux isotp socket (in your C code) to provide a padding with 0x00 as shown on stackoverflow?

**Comment by hungcuiga1** [comment]
Dear @marckleinebudde  @hartkopp ,
I can not send data have length 8192 bytes. It is error
![image](https://github.com/linux-can/can-utils/assets/44896903/6bd41cd9-554e-4f09-98c4-babdafdb7faf)
Why i think it is a vector large

**Comment by hungcuiga1** [comment]
Dear @marckleinebudde , @hartkopp 
I send 4096 bytes and I see result:
![image](https://github.com/linux-can/can-utils/assets/44896903/d3a7616b-167f-47fc-9a0d-541eb2db2a7e)
only have a line can0 seen. Please help me explain them. Thank you!

**Comment by hartkopp** [comment]
Please send the output of `uname -a` and `cat /sys/module/can_isotp/parameters/max_pdu_size`

**Comment by hungcuiga1** [comment]
Dear @hartkopp ,
I can not find ```/sys/module/can_isotp/parameters/max_pdu_size``` on ubuntu 20.04, please help me.

**Comment by hartkopp** [comment]
Please send the output of `uname -a`

**Comment by marckleinebudde** [comment]
Feel free to reopen, if you still have an issue.
