### ISSUE TITLE
CMake build broken due to ISOBUS

### ISSUE THREAD

**Issue by pschichtel** [linux-can/can-utils#497]
It seems that 42edaeaf52fdfa6af250030d5ca9e3be14764b29 might have broken the CMake build. When trying to build it, it fails with:

```
CMake Error at CMakeLists.txt:107 (add_executable):
  Cannot find source file:

    isobusfs-srv.c

  Tried extensions .c .C .c++ .cc .cpp .cxx .cu .mpp .m .M .mm .ixx .cppm
  .ccm .cxxm .c++m .h .hh .h++ .hm .hpp .hxx .in .txx .f .F .for .f77 .f90
  .f95 .f03 .hip .ispc


CMake Error at CMakeLists.txt:107 (add_executable):
  Cannot find source file:

    isobusfs-cli.c

  Tried extensions .c .C .c++ .cc .cpp .cxx .cu .mpp .m .M .mm .ixx .cppm
  .ccm .cxxm .c++m .h .hh .h++ .hm .hpp .hxx .in .txx .f .F .for .f77 .f90
  .f95 .f03 .hip .ispc


CMake Error at CMakeLists.txt:107 (add_executable):
  No SOURCES given to target: isobusfs-srv


CMake Error at CMakeLists.txt:107 (add_executable):
  No SOURCES given to target: isobusfs-cli
```

It looks for the `isobusfs-srv.c` file in root, but that file doesn't exist. `isobusfs/isobusfs_srv.c` however does exist.

**Comment by hartkopp** [comment]
@olerem I assume the problem with CMakeLists.txt is similar to the problem I fixed for the other Makefile here: 
https://github.com/linux-can/can-utils/commit/a9260eab762af9ec6c703f001252cda7487a3b66

Would you like to pick that up? I'm not really a CMake specialist.
Many thanks!

**Comment by olerem** [comment]
I'll take a look next week together with @marckleinebudde or someone who is familiar with CMake. I'm not build system expert eater :)
