### ISSUE TITLE
AutoGen.sh not found

### ISSUE THREAD

**Issue by droter** [linux-can/can-utils#5]
Hi,

When I try to generate the auto config I am getting this message:
----------
autoreconf
----------

./autogen.sh: line 20: autoreconf: command not found
viki@c3po:~/Downloads/can-utils$ ./autogen.sh 
----------
autoreconf
----------
./autogen.sh: line 20: autoreconf: command not found

**Comment by yegorich** [comment]
You are missing *autoconf* and *automake* packages. What Linux distro are you using?

**Comment by pfreitasaf** [comment]
I am having the same problem using ubuntu.

**Comment by marckleinebudde** [comment]
Try installing these packages:

    sudo aptitude install automake autoconf

**Comment by pfreitasaf** [comment]
Thanks, it solved that one problem, but now another appears:
GNUmakefile.am:25: error: Libtool library used but 'LIBTOOL' is undefined

**Comment by marckleinebudde** [comment]
Try installing these packages:

    sudo aptitude install libtool

**Comment by pfreitasaf** [comment]
Worked! Thanks!

**Comment by milad6506** [comment]
hi,
I tried all the instructions but fails in the make install process.

**Comment by marckleinebudde** [comment]
For the record:
@milad6506 opened the issue https://github.com/linux-can/can-utils/issues/12 to discuss this.
