### ISSUE TITLE
Too many build systems

### ISSUE THREAD

**Issue by marckleinebudde** [linux-can/can-utils#526]
Hey,

we have way too many build systems for this packet. I want to remove at least 1, better 2. I think I'd like to keep cmake, `Android.mk` and remove the others.

Marc

**Comment by hartkopp** [comment]
How many build systems do we really have right now?

I still like `make && make install` - but of course I have cmake on my system too.

**Comment by marckleinebudde** [comment]
Besides Android, we have autotools, cmake and plain old Makefiles.
