### ISSUE TITLE
cansend send only one frame

### ISSUE THREAD

**Issue by itachi1995** [linux-can/can-utils#72]
I am sorry but cansend send only one time just after I turn up can0 interface, in fact, I test it with oscilloscope and cansend send only one frame I am using raspbian and mcp2515 stand-alone module

**Comment by marckleinebudde** [comment]
You need proper termination, cabling and a station with the correct bit rate that wil receive the message. Otherwise the CAN chip will repeat the CAN frame over and over agian.
