### ISSUE TITLE
cannot install 

### ISSUE THREAD

**Issue by hustlerunz** [linux-can/can-utils#80]
Dear all 
i am not install driver 
i try run  ./autogen.sh but found error 

root@raspberrypi:~/can-utils# ./autogen.sh 

----------
autoreconf
----------

./autogen.sh: line 20: autoreconf: command not found
root@raspberrypi:~/can-utils# ./autogen.sh 

thank for help

**Comment by dogmatic69** [comment]
You've not got `autoreconf` installed. A simple google search would have told you that.

**Comment by yegorich** [comment]
@hustlerunz if you are running Debian 9 based disto and newer you can try: `apt install can-utils`.

You can also omit autoconf stuff and just perform: `make && make install`
