### ISSUE TITLE
Question about timeout

### ISSUE THREAD

**Issue by cedricp** [linux-can/can-utils#82]
Hi,
Not sure to ask the question in the good place, but I'm wondering if it's possible to define a timeout value for a CAN socket (as for a TCP/IP socket with SO_RCVTIMEO) for read operation.

Thank you.

**Comment by cedricp** [comment]
Thank you for your reply, and sorry, I haven't been accurate enough with my question, what I'd like to do is communicating with ISO_TP protocol, and set a read() timeout to avoid waiting a response forever.

**Comment by hartkopp** [comment]
Ok, in that case the timeout parameter of select() is what you've been searching for.

**Comment by cedricp** [comment]
Thank you so much.
