### ISSUE TITLE
What are the sX speed values?

### ISSUE THREAD

**Issue by andig** [linux-can/can-utils#84]
Would be nice to add this info to the `slcan_attach` output.

**Comment by pavel-kirienko** [comment]
0 - 10  Kbps
1 - 20  Kbps
2 - 50  Kbps
3 - 100 Kbps
4 - 125 Kbps
5 - 250 Kbps
6 - 500 Kbps
7 - 800 Kbps
8 - 1   Mbps

**Comment by yegorich** [comment]
See this tutorial https://elinux.org/Bringing_CAN_interface_up#SLCAN_based_Interfaces

**Comment by andig** [comment]
Great, thank you very much!
