### ISSUE TITLE
Setting up an interface: bit rate is half of what I specify-MPC2515

### ISSUE THREAD

**Issue by mohse-n** [linux-can/can-utils#86]
I'm using a CAN module which uses MCP2515 controller with an 8 MHz external oscillator and TJA1050 transceiver. If I set up the interface with 
`sudo ip link set can0 up type can bitrate 1000000 `
the actual bit rate is 500 Kbps. 
I have verified this in two ways. 
1- When connecting the module to a 1 Mbps CAN bus, I couldn't sniff the messages with `candump`, and couldn't communicate with the node (which was a motor drive). Lowering the bitrate of drive to 500 Kbps solved the problem.
2- Connecting an oscilloscope to high (or low) pin coming out of the transceiver, length of each bit of a CAN frame was 2 microseconds, which corresponds to a baud rate of 500 Kbps. 
I also repeated the second test with  
`sudo ip link set can0 up type can bitrate 500000`
and transferring each bit would take 4 microseconds, i.e. baud rate of 250 Kbps

**Comment by hartkopp** [comment]
This is not can-utils specific question.
Can you please post your question on the Linux-CAN mailing list to get help?

linux-can@vger.kernel.org
http://vger.kernel.org/vger-lists.html#linux-can

Thanks,
Oliver
