### ISSUE TITLE
canplayer issue with wlan

### ISSUE THREAD

**Issue by AhmedX6** [linux-can/can-utils#87]
Hello

I'm having an issue with canplayer on my android.
I have a script that launch a canplayer on a log file with can frames on system boot.

When wlan0 is created from wpa_supplicant. The canplayer accelerates the file reading.

I don't know why wlan and canplayer enters on conflict.

Even when I start after a delay I have this problem.

**Comment by hartkopp** [comment]
Hm - is it possible, that your system tries to sync the clock after WLAN is up?
The canplayer is using gettimeofday() to calculate differences of the logfile timestamp & system time.

https://github.com/linux-can/can-utils/blob/master/canplayer.c#L489

Can you check whether your system time is adjusted at runtime in your described setup?

**Comment by AhmedX6** [comment]
Hello hartkopp,

Thanks a lot for your answer.
That's indeed can be the root cause of the problem.
I'll check on that way. I'll let you know. Thank you.
