### ISSUE TITLE
Reading CAN message from specific adress

### ISSUE THREAD

**Issue by embbo** [linux-can/can-utils#89]
hi, 
Is there any file or way to read from specific CAN by read_CAN ?

**Comment by hartkopp** [comment]
Hi, what's the issue for can-utils here?

**Comment by embbo** [comment]
I can call fucntion to write can and CAN i read from the specific adress just by calling the adress.

**Comment by hartkopp** [comment]
Sorry it's not clear which tool or code you are referring to. If you have a general question to Linux and CAN please use the Linux CAN mailing list.
