### ISSUE TITLE
netlink error

### ISSUE THREAD

**Issue by drindrin4** [linux-can/can-utils#95]
hi
i use ubuntu 18.04.1
i recompiled and install can-utils from github
after create 2 vcan devices(can5,can6 ) and run
>sudo cangw -A -s can5 -d can6 -e
>netlink error -95 (Operation not supported)

**Comment by marckleinebudde** [comment]
- Which kernel version are you using?
- What's the output of `find /lib/modules/$(uname -r) -name "can-gw.ko"`
- Try `sudo modprobe can-gw` and then the `cangw` command again.

**Comment by marckleinebudde** [comment]
What was the problem?

**Comment by drindrin4** [comment]
after driver load, everythink ok
>sudo modprobe can-gw
